#!/usr/bin/env python
# This is my first script.
# pip install docker-py

import re
from docker import Client


cli = Client(base_url='unix://var/run/docker.sock')

HOSTS_PATH = 'hosts'

HOSTS_PATH = '/etc/hosts'

hosts = [['127.0.0.1', 'localhost']]
base_dns = "docker"

for cnt in cli.containers():
    name = cnt['Names'][0].replace('/','')
    if re.match(r'^box-.*', name):
      info =  cli.inspect_container(cnt['Id'])
      ipaddr = info['NetworkSettings']['IPAddress']
      full_name = "{0}.{1}".format(name, base_dns)
      hosts.append([ipaddr, full_name])

print(hosts)

f = open(HOSTS_PATH, 'w')
for x in hosts:
    f.write("{0} {1}\n".format(x[0],x[1]))
f.close()

f = open('./provision/hosts', 'w')
f.write("[app]\n")
for x in hosts[1:]:
    f.write("{0}\n".format(x[1]))
f.close()
